# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f4f33d6444b39cdea0e30dcf41b176e60743b25ac819249a54c623b7ced9b41f85c0c4b025d75515c7e20a2e59c6c1bf2051baeeccca475a1ba48ddde2abcad

test:
  secret_key_base: 1dce2b9f8b53d2a9a55447623d1ac08a883a4d20015cac8d9bd6b3e747d139a002ebce88fd48eed6ca53f3fd45f4c50c837859c15c382d7c7fd379847734f892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
